version: '3.3'

services:
  postgres:
    container_name: pg_cotibackend_container
    build: ./pgDockerSetup
    ports:
      - "5432:5432"
    # restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - postgres-data:/var/lib/postgres/data

  # backend api
  server_api:
    container_name: server_cotibackend_container
    build: 
      context: .
      dockerfile: Dockerfile.dev
    # working_dir: /usr/src/api_app
    # restart: always
    ports:
      - "4000:${WEB_API_PORT}"
    command: npm start
    volumes: 
      - .:/usr/src/api_app
      # - /usr/src/api_app/node_modules/bcrypt/
      # - /usr/src/api_app/node_modules/express-fileupload/
    depends_on:
      - postgres
    environment:
      JSONWEBTOKENSECRET: ${JSONWEBTOKENSECRET}
      PORT: ${WEB_API_PORT}

volumes:
  postgres-data: